Build.proj, Directory.Build.props, Directory.Build.targets, README.md, eng/pipelines/maintenance-packages.yml, eng/pipelines/templates/build-job.yml, global.json, src/System.Buffers/Directory.Build.props, src/System.Buffers/src/System.Buffers.csproj
cc: @ViktorHofer @carlossanlop @ericstj @bartonjs @smasher164 
This PR is addressing most of the feedback that was received during the hand-off meeting. Not shown here but has also been done: I've configured the main branch of this repo to publish to the ".NET Libraries" channel as it was requested.
The main remaining thing is the ToDo item I added on the README file, where I will add the steps on how to onboard a new library into the repo.
More specifically, these are the items that have been covered here:
- Cleanup some comments from build.proj around subsets which are not relevant.
- Fill out Readme with useful documentation as well as docs on how to service new libraries.
- Upgrade to stable 7.0 SDK
- Fix line in yml that had the wrong repo name.
- Run tests on official builds as …
=> Addressing some of the feedback that was recieved for general fixes on the repo.

build.cmd, dotnet.cmd, dotnet.sh, eng/build.ps1, eng/build.sh
- dotnet.cmd/sh allows to build with the repo local SDK
- build.sh/build.ps1 introduces the -vs switch and better switch handling.
=> Add developer innerloop scripts from runtime

.editorconfig, Directory.Build.props, src/Common/System/SR.cs, src/System.Buffers/tests/ArrayPool/ArrayPoolTest.cs, src/System.Buffers/tests/ArrayPool/UnitTests.cs
Addresses
> Enable analyzer that suggests the correct license header.
from https://github.com/dotnet/maintenance-packages/issues/16
=> Add .editorconfig

eng/packaging.targets
I'll update the affected PRs after merging this:
- https://github.com/dotnet/maintenance-packages/pull/34
- https://github.com/dotnet/maintenance-packages/pull/38
=> Add .NET Standard 1.0 and 1.3 to the baseline package validation list of frameworks to ignore

eng/packaging.targets
As mentioned in one of my PRs, this is not the same as net5.0. This tfm was used by UWP apps: https://github.com/dotnet/maintenance-packages/pull/34#discussion_r1472675288
=> Also suppress "netcore50" in package validation baseline frameworks to ignore.

Directory.Packages.props
Contains the fix introduced in https://github.com/dotnet/sdk/pull/38509
=> Update ApiCompat.Task to 9.0.100-preview.2.24102.10

eng/Version.Details.xml, eng/Versions.props, eng/common/templates-official/job/job.yml, eng/common/templates-official/job/publish-build-assets.yml, eng/pipelines/maintenance-packages.yml, global.json
This pulls in the latest 8.0 arcade and undoes the workaround for log (and manifest publishing).  The missing manifest publishing was causing our official builds to fail.
=> Fix official build publishing

.gitignore, Directory.Build.targets, eng/testing/skiptests.targets
The CI is currently attempting to wrongly execute .NET Framework tests when running in Unix due to two bugs:
1. The microsoft/vstests `VSTest` target is not bound by any conditions, so it always runs when using `dotnet test`.
2. The dotnet/arcade `RunTests` target is bound by `SkipTests` not being `true`, but is executed anyway as the Outputs depends on an item group coming from the parent target, and we don't check if the item group is empty.
This PR introduced workarounds for both cases while we get the issues in the original repos fixed and flowed here.
- RunTests PR with a fix: https://github.com/dotnet/arcade/pull/14665
- VSTest issue requesting a condition: https://github.com/microsoft/vstest/issues/4953
=> Fix CI testing in Unix

Directory.Build.targets, src/Microsoft.Bcl.HashCode/src/Microsoft.Bcl.HashCode.csproj, src/System.Buffers/src/System.Buffers.csproj, src/System.Data.SqlClient/src/System.Data.SqlClient.csproj, src/System.Data.SqlClient/tests/System.Data.SqlClient.Tests.csproj, src/System.Json/src/System.Json.csproj, src/System.Memory/src/System.Memory.csproj, src/System.Net.WebSockets.WebSocketProtocol/src/System.Net.WebSockets.WebSocketProtocol.csproj, src/System.Numerics.Vectors/src/System.Numerics.Vectors.csproj, src/System.Reflection.DispatchProxy/src/System.Reflection.DispatchProxy.csproj, src/System.Threading.Tasks.Extensions/src/System.Threading.Tasks.Extensions.csproj, src/System.Xml.XPath.XmlDocument/src/System.Xml.XPath.XmlDocument.csproj
... this should help readability and make it more
obvious what needs to change when publishing a new package.
Two unrelated changes:
1. Move the Microsoft.DotNet.Build.TargetFramework package reference directly into the projects that need it to avoid indirection.
2. Use a Choose/When construct in Microsoft.Bcl. HashCode for better readability.
=> Move package information to separate property group

Directory.Packages.props, src/System.Memory/src/System.Memory.csproj, src/System.Net.WebSockets.WebSocketProtocol/src/System.Net.WebSockets.WebSocketProtocol.csproj, src/System.Threading.Tasks.Extensions/src/System.Threading.Tasks.Extensions.csproj
Never use a prebuilt when a library is live built.
=> Use live System.Runtime.CompilerServices.Unsafe lib instead of prebuilt

Build.proj
The Build.proj condition was wrong and resulted
in test projects never being referenced and built.
Tests didn't run in CI either (no "Tests" tab):
=> Build tests in this repo

.config/CredScanSuppressions.json
Should fix the rolling build failures.
=> Exclude TdsServerCertificate.pfx from CredScan

src/Microsoft.Bcl.HashCode/src/Microsoft.Bcl.HashCode.csproj, src/Microsoft.IO.Redist/src/Microsoft.IO.Redist.csproj, src/System.Buffers/src/System.Buffers.csproj, src/System.Json/src/System.Json.csproj, src/System.Memory/src/System.Memory.csproj, src/System.Net.WebSockets.WebSocketProtocol/src/System.Net.WebSockets.WebSocketProtocol.csproj, src/System.Numerics.Vectors/src/System.Numerics.Vectors.csproj, src/System.Reflection.DispatchProxy/src/System.Reflection.DispatchProxy.csproj, src/System.Threading.Tasks.Extensions/src/System.Threading.Tasks.Extensions.csproj, src/System.Xml.XPath.XmlDocument/src/System.Xml.XPath.XmlDocument.csproj
System.Data.SqlClient is WIP: https://github.com/dotnet/maintenance-packages/pull/115
This change temporarily changed the PreReleaseVersionLabel and Iteration to preview1: https://github.com/dotnet/maintenance-packages/pull/123
This change fixed the branches that should publish signed artifacts and the ones that should only run tests: https://github.com/dotnet/maintenance-packages/pull/126
The darc default channels have been created for the branches that are expected to publish.
With the combination of those changes, we want to confirm the preview packages are pushed to the correct feed when they are turned on.
=> Generate preview version of packages (excluding System.Data.SqlClient)

src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.ilproj
Missed it in https://github.com/dotnet/maintenance-packages/pull/127
Already double checked, it's the only one I missed. It happened because I used a regex to update all the `<IsPackable>` lines in csproj files, but I forgot this one uses an ilproj.
=> Enable System.Runtime.CompilerServices.Unsafe package generation

src/System.Runtime.CompilerServices.Unsafe/Directory.Build.props, src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.ilproj
The last official build that pushed the packages to the feed, pushed version 6.0.0-preview of S.R.C.U., which is wrong: Should've been 6.1.0-preview.
We were seeing the correct package version in local builds and in the CI because in both cases, we're force-passing the /p:IsPackable=true property in the command line. But we don't do that in the official build.
I opened the fixed nupkg, then opened the two DLLs (netstandard2.0 and net462) with ILSpy, and confirmed that the correct version 6.1.0 is also stored in the metadata.
=> Move IsPackable property down to Directory.Build.props for System.Runtime.CompilerServices.Unsafe

src/System.Threading.Tasks.Extensions/src/System/Runtime/CompilerServices/ConfiguredValueTaskAwaitable.cs, src/System.Threading.Tasks.Extensions/src/System/Threading/Tasks/ValueTask.cs
`NETSTANDARD_2_0` is never defined, but `NETSTANDARD2_0` is.
=> Fix NETSTANDARD2 define in S.T.T.E

Directory.Build.targets, src/Microsoft.Bcl.HashCode/src/Microsoft.Bcl.HashCode.xml, src/Microsoft.IO.Redist/src/Microsoft.IO.Redist.csproj, src/System.Buffers/src/System.Buffers.xml, src/System.Data.SqlClient/src/System.Data.SqlClient.xml, src/System.Json/src/System.Json.xml, src/System.Memory/src/System.Memory.xml, src/System.Net.WebSockets.WebSocketProtocol/src/System.Net.WebSockets.WebSocketProtocol.xml, src/System.Numerics.Vectors/src/System.Numerics.Vectors.xml, src/System.Reflection.DispatchProxy/src/System.Reflection.DispatchProxy.xml, src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.ilproj, src/System.Runtime.CompilerServices.Unsafe/ver/System.Runtime.CompilerServices.Unsafe.xml, src/System.Threading.Tasks.Extensions/src/System.Threading.Tasks.Extensions.xml, src/System.Xml.XPath.XmlDocument/src/System.Xml.XPath.XmlDocument.xml
Fixes https://github.com/dotnet/maintenance-packages/issues/133
Currently the repo is not autogenerating the intellisense xmls out of the triple slash comments.
Two assemblies, Microsoft.IO.Redist and System.Runtime.CompilerServices.Unsafe, already had an xml file commited in the src folder and explicitly included in the csproj. So I brought all the xmls in the last nupkg releases of all the other assemblies, and moved the DocumentationFile property down to the root directory.
I published the packages locally and was able to confirm that they now include their respective xmls inside each of the lib/<tfm>/ folders (only when there is a valid dll, not when there are placeholders).
=> Bring back the intellisense xmls

Directory.Build.targets
Fixes https://github.com/dotnet/maintenance-packages/issues/147
The Default behavior in VS is to show files for the first target framework in TargetFrameworks property. This is required to show all the files corresponding to all target frameworks in VS.
https://github.com/dotnet/project-system/issues/935
With this change:
=> Don't filter files to show in VS

src/System.Xml.XPath.XmlDocument/src/System.Xml.XPath.XmlDocument.csproj
Fixes https://github.com/dotnet/maintenance-packages/issues/100
Before:
- [assembly: AssemblyFileVersion("4.6.24705.01")]
- [assembly: AssemblyInformationalVersion("4.6.24705.01. Commit Hash: 4d1af962ca0fede10beb01d197367c2f90e92c97")]
- [assembly: AssemblyVersion("4.0.2.0")]
After:
- [assembly: AssemblyFileVersion("4.700.24.52901")]
- [assembly: AssemblyInformationalVersion("4.7.0-dev.24529.1+f2633cbdb1640f2588165f27e9a97a113ec3780f")]
- [assembly: AssemblyVersion("4.0.3.0")]
Note that in this change I'm using:
- VersionPrefix = 4.3.0 
- VersionPrefix (with IsPackable=true) = 4.7.0
This helped me ensure that AssemblyInformationalVersion was greater than in the last release. I do not know where that 4.6 is coming from.
I tried using VersionPrefix = 4.6.0 but I get the error below, so I …
=> Fix assembly informational version in System.Xml.XPath.XmlDocument

eng/Signing.props
I noticed runtime does some additional work in eng/Signing.props (release/9.0) that we don't have here, so I'm bringing it: https://github.com/dotnet/runtime/blob/release/9.0/eng/Signing.props
- Empty the default ItemsToSign
- Exclude *symbols.nupkg files from signing
- Update all the default arcade items that use a CertificateName Microsoft400 to use the .NET-specific certificate
- Finally, on the condition of IsPackable==true (_in runtime, it uses PrepareArtifacts==true, which is set by the installer in runtime, we don't have it here_):
- Mark all the artifacts nupkgs to sign post build without their full path
- Mark all the artifacts nupkgs to sign (not post build) with their full path
Note: Locally, signing is done with DryRun enabled, so nothing really happens:
```
$ signtool verify …
```
=> Bring missing signing configuration

eng/Versions.props
I missed this property in my previous PR. Without it, the packages are still getting pushed to the `dotnet-libraries` feed with the prerelease qualifiers and the patch version in their names. Example: https://dnceng.visualstudio.com/public/_artifacts/feed/dotnet-libraries/NuGet/System.Numerics.Vectors/overview/4.6.0-rtm.24531.3
After merging this, each release will be pushed to its own isolated feed, and the package names will not contain any prerelease qualifiers and patch versions in their names.
We don't have to merge this right away. Let's wait until we finish fine tuning the last details in the repo.
=> Enable DotNetFinalVersionKind to remove the patch version and prerelease qualifiers from package names

eng/Versions.props
We were able to confirm that the stable builds work as expected. [The commit](https://github.com/dotnet/maintenance-packages/commit/a8adb65c79e4ce8df1614563f872be189b6dbdbe) in `main` that set the `DotNetFinalVersionKind` property to `release` caused the expected things to happen:
- The prerelease/preview suffix was removed from the package versions: https://product-construction-prod.wittysky-0c79e3cc.westus2.azurecontainerapps.io/channel/1648/github:dotnet:maintenance-packages/build/latest
- The `dotnet-libraries` feed stopped being used for publishing the packages. As an example, Microsoft.Bcl.HashCode still shows the rtm as the last package published (before the commit mentioned above). https://dnceng.visualstudio.com/public/_artifacts/feed/dotnet-libraries/NuGet/Microsoft.Bcl.HashCode/ …
=> Revert setting DotNetFinalVersionKind to release

src/Microsoft.IO.Redist/src/Microsoft.IO.Redist.csproj
Let it get calculated based on VersionPrefix same as Microsoft.Bcl.HashCode already does.
=> Remove hardcoded AssemblyVersion from Microsoft.IO.Redist

src/System.Json/src/System.Json.csproj
Align the package and assembly version for System.Json by upgrading the assembly version from 2.0.8.0 to 4.8.0.0.
=> Remove hardcoded assembly version from System.Json

eng/Versions.props, eng/pipelines/maintenance-packages.yml
For easier manipulation when we want to generate stable packages.
=> Pass DotNetFinalVersionKind via yaml as a global property

eng/pipelines/common-variables.yml
PostBuildSigning requires an [additional release and signing step](https://github.com/dotnet/arcade/blob/488a796fd621ef6a81ef08f27e32ae43af1bb96c/Documentation/CorePackages/PostBuildSigning.md) after build.  We aren't doing that for maintenance-packages, so just sign during the build.
=> Remove PostBuildSign

src/System.Runtime.CompilerServices.Unsafe/Versioning.props, src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.ilproj
Fixes https://github.com/dotnet/maintenance-packages/issues/174
Here's the comparison of the last DLL shipped out of release/6.0 (first tree item & left tab) vs the m-p version with the fix in this PR (second tree item vs right tab):
And the Unsafe type shows all the same APIs too.
=> Bring back net6.0 TFM to System.Runtime.CompilerServices.Unsafe

src/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxy.cs
Fixes https://github.com/dotnet/maintenance-packages/issues/194
This is what ILSpy shows for the DLL of the nupkg version 4.7.0:
=> Fix DispatchProxy.Invoke for .NET Standard 2.0

.github/workflows/check-no-merge-label.yml
Matches the workflow we have in runtime: https://github.com/dotnet/runtime/blob/release/8.0/.github/workflows/check-no-merge-label.yml
Note that the label in maintenance-packages is not `NO-MERGE`, but `NO MERGE`: https://github.com/dotnet/maintenance-packages/labels
My understanding from @jeffhandley 's explanation is that the current PR won't be able to test this workflow. It will have to be tested after merging, either with currently open PRs (which will require pressing the workflow approval in the CI section) or in subsequent PRs.
=> Add a workflow that checks for the 'NO MERGE' label and prevents PR merge

src/Microsoft.IO.Redist/src/Microsoft.IO.Redist.csproj, src/System.Buffers/src/System.Buffers.csproj, src/System.Memory/src/System.Memory.csproj, src/System.Net.WebSockets.WebSocketProtocol/src/System.Net.WebSockets.WebSocketProtocol.csproj, src/System.Numerics.Vectors/src/System.Numerics.Vectors.csproj, src/System.Reflection.DispatchProxy/src/System.Reflection.DispatchProxy.Forwards.cs, src/System.Reflection.DispatchProxy/src/System.Reflection.DispatchProxy.csproj, src/System.Runtime.CompilerServices.Unsafe/Versioning.props, src/System.Threading.Tasks.Extensions/src/System.Threading.Tasks.Extensions.csproj
Fixes https://github.com/dotnet/maintenance-packages/issues/212
- Remove netcoreapp placeholders when there's already a .NET Standard placeholder.
- Mark libraries as packable
- Simplify placeholder conditions
- Add a placeholder for dispatchproxy netcoreapp2.0 and netstandard2.1 and remove type forwards.
=> Add netstandard2.1 placeholders

src/System.ValueTuple/src/System.ValueTuple.csproj, src/System.ValueTuple/src/buildTransitive/net471/System.ValueTuple.targets
Fixes https://github.com/dotnet/maintenance-packages/issues/213
System.ValueTuple is inbox on .NET Framework >= 4.7.1 and therefore any potential redirect for it should be removed. This is necessary as the assembly version in the already shipped packages is higher than what's provided inbox on .NET Framework
Package layout:
=> Fix ValueTuple consumption on >= net471

src/Microsoft.IO.Redist/src/Microsoft.IO.Redist.csproj, src/System.Buffers/src/System.Buffers.csproj, src/System.Memory/src/System.Memory.csproj, src/System.Net.WebSockets.WebSocketProtocol/src/System.Net.WebSockets.WebSocketProtocol.csproj, src/System.Numerics.Vectors/src/System.Numerics.Vectors.csproj, src/System.Reflection.DispatchProxy/src/System.Reflection.DispatchProxy.csproj, src/System.Threading.Tasks.Extensions/src/System.Threading.Tasks.Extensions.csproj, src/System.ValueTuple/src/System.ValueTuple.csproj
The ost recent versions in nuget.org are:
- Microsoft.IO.Redist 6.1.2
- System.Buffers 4.6.1
- System.Memory 4.6.2
- System.Net.WebSockets.WebSocketProtocol 5.1.2
- System.Numerics.Vectors 4.6.1
- System.Reflection.DispatchProxy 4.8.2
- System.Threading.Tasks.Extensions 4.6.2
- System.ValueTuple 4.6.1
This was done manually. I have an issue open to track the work to automate these PRs: https://github.com/dotnet/maintenance-packages/issues/217
=> Turn off packages and bump versions

src/Microsoft.IO.Redist/src/Microsoft.IO.Redist.csproj, src/System.Memory/src/System.Memory.csproj, src/System.Net.WebSockets.WebSocketProtocol/src/System.Net.WebSockets.WebSocketProtocol.csproj, src/System.Runtime.CompilerServices.Unsafe/Versioning.props, src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.ilproj, src/System.Runtime.CompilerServices.Unsafe/ver/Versioning.csproj, src/System.Threading.Tasks.Extensions/src/System.Threading.Tasks.Extensions.csproj
This was missed due to being in a separate file.
These will now be in the same file as the other versioning ones, and will also affect the tests and resource versions but that would not be a problem.
=> Fix S.R.CS.Unsafe AssemblyVersion and move properties to Versioning.props

src/System.Data.SqlClient/src/PACKAGE.md
I noticed poorly formatted markdown when  reading the SqlClient readme.
=> Fix SqlClient package readme markdown
